#!/bin/csh -f

# This software was developed by employees of the National Institute 
# of Standards and Technology (NIST), an agency of the Federal 
# Government and is being made available as a public service. Pursuant 
# to title 17 United States Code Section 105, works of NIST employees 
# are not subject to copyright protection in the United States.  This 
# software may be subject to foreign copyright.  Permission in the 
# United States and in foreign countries, to the extent that NIST may 
# hold copyright, to use, copy, modify, create derivative works, and 
# distribute this software and its documentation without fee is hereby 
# granted on a non-exclusive basis, provided that this notice and 
# disclaimer of warranty appears in all copies. 

# THE SOFTWARE IS PROVIDED 'AS IS' WITHOUT ANY WARRANTY OF ANY KIND, 
# EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED 
# TO, ANY WARRANTY THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS, 
# ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
# PURPOSE, AND FREEDOM FROM INFRINGEMENT, AND ANY WARRANTY THAT THE 
# DOCUMENTATION WILL CONFORM TO THE SOFTWARE, OR ANY WARRANTY THAT THE 
# SOFTWARE WILL BE ERROR FREE.  IN NO EVENT SHALL NIST BE LIABLE FOR 
# ANY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, SPECIAL 
# OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM, OR IN ANY 
# WAY CONNECTED WITH THIS SOFTWARE, WHETHER OR NOT BASED UPON WARRANTY, 
# CONTRACT, TORT, OR OTHERWISE, WHETHER OR NOT INJURY WAS SUSTAINED BY 
# PERSONS OR PROPERTY OR OTHERWISE, AND WHETHER OR NOT LOSS WAS 
# SUSTAINED FROM, OR AROSE OUT OF THE RESULTS OF, OR USE OF, THE 
# SOFTWARE OR SERVICES PROVIDED HEREUNDER.

#                   	 "@(#)visit-prep	1.2  8/17/95"
#
#****************************************************************
#                                                               *
#  Unravel Project: Develop a program slicer for ANSI C         *
#                                                               *
#  Developed at N.I.S.T. Computer Systems Lab by:               *
#                                                               *
#      D. Wallace     Project Leader                            *
#                                                               *
#      J. Lyle, J. Graham, K. Gallagher, D. Binkley & J. Poole  *
#                                                               *
#****************************************************************
#  This is visit-prep  used to create vprep                     *
#  vprep  setup visit order of nodes                            *
#                                                               *
#                                                               *
#                                                               *
#****************************************************************
set path = (HOME $path)
foreach v ($argv)
#	cat $v:r.LIF | grep "^16" |\
#		sed -e "s/16(//" -e "s/,/ /" -e 's/).*$//' | vsort >& $v:r.V
	set procs = `visit-ctrl $v:r.T`
#	/bin/rm -f V Va Vb V1
	/bin/rm -f $v:r.V
	while ($#procs)
		set from = $procs[1]
		set to = $procs[2]
		shift procs
		shift procs
#		echo "======= $from $to ==========" >>Va
		cat $v:r.LIF | grep "^16" |\
			sed -e "s/16(//" -e "s/,/ /" -e 's/).*$//' |\
			visit-filter $from $to | \
			vsort | nl | sort -n -r |\
			sed -e 's/^ *[0-9]*[ 	]*//' |\
			visit-post $from $to >> $v:r.V
#			sed -e "s/16(//" -e "s/,/ /" -e 's/).*$//' | tee V1 |\
#			visit-filter $from $to | tee -a V |\
#			vsort | cat -n |tee -a Va | sort -n -r | tee -a Vb |\
#			vsort |& tee -a V | visit-post $from $to >> $v:r.V
	end
end
